function [sliderHandle] = addSlider(panel, val, valRange, options)
%Add slider to figure or panel.
% The slider will additionally have edit fields for min, max, and current
% value. The min and max values can be editable or not depending on
% settings.
%
% This is for nLayerViewer.
% 
% Author: Matt Dvorsky

arguments
    panel(1, 1);
    val(1, 1);
    valRange(2, 1);

    options.ValueChangedHandler = @(val) val;

    options.SliderWidth(1, 1) = 0.6;
    options.SliderHeight(1, 1) = 0.12;

    options.SliderHeightOffset(1, 1) = 0;
end

%% Create Slider
sliderHandle = uicontrol(Parent=panel, ...
    Style="slider", Units="normalized", ...
    Position=[...
        0.15, ...
        1 - options.SliderHeightOffset - options.SliderHeight, ...
        options.SliderWidth, ...
        options.SliderHeight, ...
    ]);

%% Create Edit Fields
currentValueField = uicontrol(Style="edit", ...
    Parent=panel, Units="Normalized", ...
    Value=val, ...
    String=num2str(val), ...
    Position=[...
        0.87, ...
        1 - options.SliderHeightOffset - options.SliderHeight, ...
        0.1, ...
        options.SliderHeight, ...
    ]);

lowerBoundField = uicontrol(Style="edit", ...
    Parent=panel, Units="Normalized", ...
    Value=min(valRange), ...
    String=num2str(min(valRange)), ...
    Position=[...
        0.05, ...
        1 - options.SliderHeightOffset - options.SliderHeight, ...
        0.1, ...
        options.SliderHeight, ...
    ]);

upperBoundField = uicontrol(Style="edit", ...
    Parent=panel, Units="Normalized", ...
    Value=max(valRange), ...
    String=num2str(max(valRange)), ...
    Position=[...
        0.75, ...
        1 - options.SliderHeightOffset - options.SliderHeight, ...
        0.1, ...
        options.SliderHeight, ...
    ]);

%% Setup CallBacks
sliderHandle.Callback = {@sliderCallback, ...
    sliderHandle, currentValueField, lowerBoundField, upperBoundField, ...
    options.ValueChangedHandler};

currentValueField.Callback = {@fieldCallback, ...
    sliderHandle, currentValueField, lowerBoundField, upperBoundField, ...
    options.ValueChangedHandler};
lowerBoundField.Callback = {@fieldCallback, ...
    sliderHandle, currentValueField, lowerBoundField, upperBoundField, ...
    options.ValueChangedHandler};
upperBoundField.Callback = {@fieldCallback, ...
    sliderHandle, currentValueField, lowerBoundField, upperBoundField, ...
    options.ValueChangedHandler};

end




%% Callbacks
function valueChangedCallback(val, userCallback)
    if iscell(userCallback)
        userCallback{1}(val, userCallback{2:end});
    else
        userCallback(val);
    end
end

function sliderCallback(~, ~, slider, cvField, minField, maxField, userCallback)
    minVal = minField.Value;
    maxVal = maxField.Value;

    cvField.Value = minVal + (maxVal - minVal)*slider.Value;
    cvField.String = num2str(cvField.Value);

    valueChangedCallback(cvField.Value, userCallback);
end

function fieldCallback(src, ~, slider, cvField, minField, maxField, userCallback)
    src.Value = str2double(src.String);

    currentVal = cvField.Value;
    minVal = minField.Value;
    maxVal = maxField.Value;

    slider.Value = max(0, min(1, ...
        (currentVal - minVal) ./ (maxVal - minVal)));

    if src == cvField
        valueChangedCallback(cvField.Value, userCallback);
    end
end




